---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wikied-be
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: wikied-be
  template:
    metadata:
      labels:
        name: wikied-be
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: wikied-be
        image: docker.io/cosmycx/wikied-be
        imagePullPolicy: Always
        ports:
        - containerPort: 4040



