---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
          - sysctl
          - -w
          - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.io/elasticsearch:7.3.0
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: node-node
        resources:
          requests:
            memory: 8Gi
          limits:
            memory: 16Gi
            cpu: 1