---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9200
  - name: node-node
    port: 9300
    targetPort: 9200
  selector: 
    name: elasticsearch